services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    build:
      context: ./server
    ports:
      - 5035:5035
    develop:
      watch:
        - action: sync
          path: ./server
          target: /server
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgresdb"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  # web:
  #   build:
  #     context: ./web
  #   depends_on:
  #     - server
  #   ports:
  #     - 3000:3000
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./web
  #         target: /web
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: package.json
  #   stdin_open: true
  #   tty: true

volumes:
  postgres-data: